### ISSUE TITLE
You can upload Server + Client + DB + Tools again?

### ISSUE THREAD

**Issue by Pxthaphi** [imhatepython/Raycity#1]
You can upload Server + Client + DB + Tools again? My client can't login to field it stuck at garage.

![Screenshot 2022-06-25 214212](https://user-images.githubusercontent.com/97496065/175778487-8bed269b-90f5-43a9-86ae-6ffba20f3b70.png)

Or do you have another solution help me? 
Thx CandyElaina

**Comment by CandyElaina** [comment]
It's probably because of the forced conversion of vehicles in the database

It seems to be a problem that can be solved by re-registering the database.

I hope the problem goes well

**Comment by imhatepython** [comment]
You have uploaded a new file

Sorry for the late upload due to personal circumstances

https://drive.google.com/file/d/1OfNaw38EOSfhIWuixs0CWiziDXXGeREV/view?usp=sharing
