### ISSUE TITLE
Pls help for step install

### ISSUE THREAD

**Issue by ghostprize** [imhatepython/Raycity#2]
i need installation step
Pls.

**Comment by imhatepython** [comment]
1.Microsoft Sql Server 2019 install
2.Database Restore
(https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/restore-a-database-backup-using-ssms?view=sql-server-ver16)
3.Sql Server Configuration Manager ->  SQL Native Client 11.0 -> Client protocol Change all to Enabled
-------------------
CenterServer - config.xml info_server.xml
GameServer , Agent - config.xml
enter your IP
To connect the DB to the center server you must enter the server address, ID, ,password in config.xml
--------------------
tools -> Daily Tools -> thunterhk.exe -> Client -> 0m decrypt -> Raycity.0m Select
(https://mh-nexus.de/en/downloads.php?product=HxD20)
Modify the server IP and port through HxD
Change the Port from 2180 to 2080
thunterhk.exe -> Client -> 0m encrypt

**Comment by ghostprize** [comment]
What files will I need to use HxD for?
[HxDSetup.zip](https://github.com/imhatepython/Raycity/files/9993916/HxDSetup.zip)
What do I do next while I'm in the game and I still can't see the server I have named?

I'm not sure if I connected the database correctly.
Because before I used IP address 127.0.0.1 thunterhk.exe has GS loop running, but I use IP as DESKTOP-VMKM7V8\SQLEXPRESS. I didn't see any errors running it. thunterhk.exe

And thank you very much for your help.

**Comment by ghostprize** [comment]
My CS
-----------------------------------------------------------------------
<?xml version='1.0' encoding='UTF-16'?>
<config>
	<host name='RayCity [THunterHK]' port='2080' authenKey='thunterhk'/>
	<Scheduler>
		<Job Name='AutoMailReturn' Type='0'>
			<Timer H='7' M='0' S='0'/>
		</Job>
                     <Job Name='ReportWorker' Type='0'>
                                <Timer H='0' M='0' S='0'/>
                                <Timer H='6' M='0' S='0'/>
                                <Timer H='12' M='0' S='0'/>
                                <Timer H='18' M='0' S='0'/>
                     </Job>
	</Scheduler>
	<slaveNote>
		<worldId>2</worldId>
		<countryCode>sg</countryCode>
		<MaxUserCount>500</MaxUserCount>
		<LuckySpot>
			<LuckySpotPercentage>30</LuckySpotPercentage>
			<LuckySpPercentage>30</LuckySpPercentage>
		</LuckySpot>
		<globalDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GlobalAccount' account='sa' password='x'/>
		<gameDefDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameDefinition' account='sa' password='x'/>
		<gameStatDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameStat' account='sa' password='x'/>
		<gameReportDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameReport' account='sa' password='x'/>
		<couponDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameCoupon' account='sa' password='x'/>
		<ICafeIPListDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GlobalAccount' account='sa' password='x'/>
		<eventDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameEvent' account='sa' password='x'/>
		<gameDbList>
			<gameDb idx='0' ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameDB00' account='sa' password='x'/>
			<logDb idx='0' ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameLog00' account='sa' password='x'/>
		</gameDbList>
	</slaveNote>
</config>

------------------------------------------------------------------------
CS > info_server.xml

<?xml version='1.0'  encoding='UTF-16'?>
<server>
	<global>
		<messenger>
			<ip>127.0.0.1</ip>
			<port>2183</port>
		</messenger>
		<race>
			<ip>127.0.0.1</ip>
			<port>2184</port>
		</race>
		<auction>
			<ip>127.0.0.1</ip>
			<port>2185</port>
		</auction>
	</global>

	<channels>
		<channel>
			<name>Server 999</name>
			<ip>127.0.0.1</ip>
			<port>2080</port>
			<MaxFill>10</MaxFill>
			<agent>
				<traffic><port>2181</port></traffic>
				<chat><port>2182</port></chat>
			</agent>
		</channel>



	</channels>
</server>

**Comment by ghostprize** [comment]
My CS
-------------------------------------------------------------
<?xml version='1.0' encoding='UTF-16'?>
<config>
	<host name='RayCity [THunterHK]' port='2080' authenKey='thunterhk'/>
	<Scheduler>
		<Job Name='AutoMailReturn' Type='0'>
			<Timer H='7' M='0' S='0'/>
		</Job>
                     <Job Name='ReportWorker' Type='0'>
                                <Timer H='0' M='0' S='0'/>
                                <Timer H='6' M='0' S='0'/>
                                <Timer H='12' M='0' S='0'/>
                                <Timer H='18' M='0' S='0'/>
                     </Job>
	</Scheduler>
	<slaveNote>
		<worldId>2</worldId>
		<countryCode>sg</countryCode>
		<MaxUserCount>500</MaxUserCount>
		<LuckySpot>
			<LuckySpotPercentage>30</LuckySpotPercentage>
			<LuckySpPercentage>30</LuckySpPercentage>
		</LuckySpot>
		<globalDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GlobalAccount' account='sa' password='x'/>
		<gameDefDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameDefinition' account='sa' password='x'/>
		<gameStatDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameStat' account='sa' password='x'/>
		<gameReportDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameReport' account='sa' password='x'/>
		<couponDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameCoupon' account='sa' password='x'/>
		<ICafeIPListDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GlobalAccount' account='sa' password='x'/>
		<eventDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameEvent' account='sa' password='x'/>
		<gameDbList>
			<gameDb idx='0' ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameDB00' account='sa' password='x'/>
			<logDb idx='0' ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameLog00' account='sa' password='x'/>
		</gameDbList>
	</slaveNote>
</config>

**Comment by ghostprize** [comment]
<?xml version='1.0' encoding='UTF-16'?>
<config>
	<host name='RayCity [THunterHK]' port='2080' authenKey='thunterhk'/>
	<Scheduler>
		<Job Name='AutoMailReturn' Type='0'>
			<Timer H='7' M='0' S='0'/>
		</Job>
                     <Job Name='ReportWorker' Type='0'>
                                <Timer H='0' M='0' S='0'/>
                                <Timer H='6' M='0' S='0'/>
                                <Timer H='12' M='0' S='0'/>
                                <Timer H='18' M='0' S='0'/>
                     </Job>
	</Scheduler>
	<slaveNote>
		<worldId>2</worldId>
		<countryCode>sg</countryCode>
		<MaxUserCount>500</MaxUserCount>
		<LuckySpot>
			<LuckySpotPercentage>30</LuckySpotPercentage>
			<LuckySpPercentage>30</LuckySpPercentage>
		</LuckySpot>
		<globalDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GlobalAccount' account='sa' password='x'/>
		<gameDefDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameDefinition' account='sa' password='x'/>
		<gameStatDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameStat' account='sa' password='x'/>
		<gameReportDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameReport' account='sa' password='x'/>
		<couponDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameCoupon' account='sa' password='x'/>
		<ICafeIPListDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GlobalAccount' account='sa' password='x'/>
		<eventDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameEvent' account='sa' password='x'/>
		<gameDbList>
			<gameDb idx='0' ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameDB00' account='sa' password='x'/>
			<logDb idx='0' ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameLog00' account='sa' password='x'/>
		</gameDbList>
	</slaveNote>
</config>

**Comment by ghostprize** [comment]
My CS
***************************************
`<?xml version='1.0' encoding='UTF-16'?>
<config>
	<host name='RayCity [THunterHK]' port='2080' authenKey='thunterhk'/>
	<Scheduler>
		<Job Name='AutoMailReturn' Type='0'>
			<Timer H='7' M='0' S='0'/>
		</Job>
                     <Job Name='ReportWorker' Type='0'>
                                <Timer H='0' M='0' S='0'/>
                                <Timer H='6' M='0' S='0'/>
                                <Timer H='12' M='0' S='0'/>
                                <Timer H='18' M='0' S='0'/>
                     </Job>
	</Scheduler>
	<slaveNote>
		<worldId>2</worldId>
		<countryCode>sg</countryCode>
		<MaxUserCount>500</MaxUserCount>
		<LuckySpot>
			<LuckySpotPercentage>30</LuckySpotPercentage>
			<LuckySpPercentage>30</LuckySpPercentage>
		</LuckySpot>
		<globalDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GlobalAccount' account='sa' password='x'/>
		<gameDefDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameDefinition' account='sa' password='x'/>
		<gameStatDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameStat' account='sa' password='x'/>
		<gameReportDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameReport' account='sa' password='x'/>
		<couponDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameCoupon' account='sa' password='x'/>
		<ICafeIPListDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GlobalAccount' account='sa' password='x'/>
		<eventDb ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameEvent' account='sa' password='x'/>
		<gameDbList>
			<gameDb idx='0' ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameDB00' account='sa' password='x'/>
			<logDb idx='0' ip='DESKTOP-VMKM7V8\SQLEXPRESS' dbName='GameLog00' account='sa' password='x'/>
		</gameDbList>
	</slaveNote>
</config>
`

**Comment by imhatepython** [comment]
Perhaps the database is not properly connected to the server
If you use the server file I uploaded, you can build the server the method I described

**Comment by imhatepython** [comment]
And if I use localhost (127.0.0.1), the server name and channel specified in CS do not appear

**Comment by ghostprize** [comment]
Do you have Discord ?
I still can't login to the server.

**Comment by ghostprize** [comment]
What files do I need to open to edit using HxD?
