### ISSUE TITLE
I have some questions I'd like to ask.

### ISSUE THREAD

**Issue by ghostprize** [imhatepython/Raycity#3]
I can now run in the map.
I want to ask if the database is not complete yet? I can't use the capsule yet and any item that opens or changes the value of the item will notify me that Inventory is full

And I want to help develop it, please continue to develop it.
thank

**Comment by imhatepython** [comment]
The database used for the current project is incomplete and
Lots of bugs. Currently development is not in progress due to personal circumstances so you have to fix bugs yourself

**Comment by ghostprize** [comment]
Every item in the database is dated, I want it to be permanent.

**Comment by imhatepython** [comment]
GameDB00 > procedure > GetInventoryItem , AS_BuyCashItem , BuyItem

**Comment by ghostprize** [comment]
![Capture](https://user-images.githubusercontent.com/95231293/204802535-122052c9-0f0f-4df7-a876-56ac1e40c3a2.PNG)
I still don't quite understand how I can fix it.
All items purchased from the shop have an expiration date.

Please help me to solve this problem or is there a database that you updated more please upload it again?

**Comment by imhatepython** [comment]
I'll take care of it later when the time comes
